name: Build

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --editable .
        pip install build 
    - name: Run tests
      run: |
        coverage run -m pytest
    - name: Build Docker images
      uses: docker/build-push-action@v2.5.0
